import { Colors } from "@/constants/colors";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    horizontalContainer: { height: 105, flexDirection: "row", gap: 12, alignItems: "center" },
    verticalContainer: { width: 120 },
    posterContainer: { aspectRatio: 2 / 3, borderRadius: 12, overflow: "hidden", backgroundColor: Colors.surface },
    infoWrapper: { flex: 1, justifyContent: "center" },
    horizontalPosterContainer: { height: 105 },
    verticalPosterContainer: { width: "100%" },
    poster: { width: "100%", height: "100%" },
    placeholderContainer: {
        width: "100%",
        height: "100%",
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: Colors.surface,
    },
    badgeContainer: {
        position: "absolute",
        bottom: 6,
        left: 6,
        right: 6,
        flexDirection: "row",
        flexWrap: "wrap",
        alignItems: "center",
        gap: 4,
    },
    badgeItem: {
        height: 20,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: "rgba(0, 0, 0, 0.75)",
        borderWidth: 1,
        borderColor: "rgba(245, 158, 11, 0.5)",
        paddingHorizontal: 5,
        borderRadius: 5,
    },
    badgeText: { fontSize: 11, fontWeight: "bold", marginLeft: 3, includeFontPadding: false },
    title: { color: Colors.textPrimary, fontSize: 12, fontWeight: "600", marginTop: 6, lineHeight: 16 },
    horizontalTitle: { fontSize: 14, marginBottom: 4 },
    compactTitle: { fontSize: 11.5, fontWeight: "600", marginTop: 4, lineHeight: 15 },
    genres: { fontSize: 12, color: Colors.textSecondary, marginBottom: 4 },
    subTitle: { color: Colors.textSecondary, fontSize: 12, marginTop: 2 },
    compactSubTitle: { fontSize: 10, marginTop: 1, lineHeight: 13 },
});
