import { StyleSheet } from "react-native";
import { Colors } from "@/constants/colors";

export const styles = StyleSheet.create({
    container: {
        paddingHorizontal: 20,
        paddingBottom: 32,
        paddingTop: 8,
    },
    subtitle: {
        fontSize: 14,
        color: Colors.textSecondary,
        marginBottom: 20,
        lineHeight: 20,
    },
    errorBanner: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "rgba(239, 68, 68, 0.12)",
        borderColor: "rgba(239, 68, 68, 0.3)",
        borderWidth: 1,
        borderRadius: 12,
        padding: 12,
        marginBottom: 16,
        gap: 10,
    },
    errorText: {
        flex: 1,
        color: Colors.danger,
        fontSize: 13,
        lineHeight: 18,
    },
    guideCard: {
        backgroundColor: Colors.surfaceLight,
        borderRadius: 16,
        padding: 16,
        borderWidth: 1,
        borderColor: Colors.border,
        marginBottom: 20,
    },
    guideTitle: {
        fontSize: 15,
        fontWeight: "600",
        color: Colors.textPrimary,
        marginBottom: 14,
    },
    stepRow: {
        flexDirection: "row",
        alignItems: "flex-start",
        marginBottom: 12,
        gap: 12,
    },
    stepBadge: {
        width: 24,
        height: 24,
        borderRadius: 12,
        backgroundColor: "rgba(74, 158, 255, 0.15)",
        borderWidth: 1,
        borderColor: "rgba(74, 158, 255, 0.3)",
        alignItems: "center",
        justifyContent: "center",
        marginTop: 1,
    },
    stepBadgeText: {
        fontSize: 12,
        fontWeight: "700",
        color: Colors.primary,
    },
    stepText: {
        flex: 1,
        fontSize: 13,
        color: Colors.textPrimary,
        lineHeight: 20,
    },
    openLinkButton: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: "rgba(255, 255, 255, 0.06)",
        borderWidth: 1,
        borderColor: Colors.border,
        borderRadius: 12,
        paddingVertical: 12,
        marginBottom: 14,
        gap: 8,
    },
    openLinkText: {
        fontSize: 14,
        fontWeight: "600",
        color: Colors.textPrimary,
    },
    uploadButton: {
        backgroundColor: Colors.primary,
        borderRadius: 12,
        paddingVertical: 14,
        alignItems: "center",
        justifyContent: "center",
    },
    uploadButtonText: {
        fontSize: 15,
        fontWeight: "700",
        color: "#FFFFFF",
    },
    // Progress Screen
    progressContainer: {
        alignItems: "center",
        paddingVertical: 20,
    },
    progressIconContainer: {
        width: 64,
        height: 64,
        borderRadius: 32,
        backgroundColor: "rgba(74, 158, 255, 0.12)",
        borderWidth: 1,
        borderColor: "rgba(74, 158, 255, 0.25)",
        alignItems: "center",
        justifyContent: "center",
        marginBottom: 16,
    },
    progressTitle: {
        fontSize: 17,
        fontWeight: "700",
        color: Colors.textPrimary,
        marginBottom: 8,
        textAlign: "center",
    },
    progressSubtitle: {
        fontSize: 14,
        color: Colors.textSecondary,
        marginBottom: 24,
        textAlign: "center",
    },
    progressBarTrack: {
        width: "100%",
        height: 10,
        backgroundColor: "rgba(255, 255, 255, 0.08)",
        borderRadius: 5,
        overflow: "hidden",
        marginBottom: 14,
    },
    progressBarFill: {
        height: "100%",
        backgroundColor: Colors.primary,
        borderRadius: 5,
    },
    progressStatsRow: {
        flexDirection: "row",
        justifyContent: "space-between",
        width: "100%",
        marginBottom: 20,
    },
    progressStatText: {
        fontSize: 13,
        color: Colors.textSecondary,
        fontWeight: "500",
    },
    progressStatValue: {
        color: Colors.textPrimary,
        fontWeight: "600",
    },
    backgroundInfoBox: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "rgba(74, 158, 255, 0.08)",
        borderRadius: 12,
        padding: 12,
        gap: 10,
        marginBottom: 20,
    },
    backgroundInfoText: {
        flex: 1,
        fontSize: 12,
        color: Colors.textSecondary,
        lineHeight: 18,
    },
    backgroundButton: {
        width: "100%",
        backgroundColor: "rgba(255, 255, 255, 0.08)",
        borderRadius: 12,
        paddingVertical: 14,
        alignItems: "center",
        justifyContent: "center",
        borderWidth: 1,
        borderColor: Colors.border,
    },
    backgroundButtonText: {
        fontSize: 15,
        fontWeight: "600",
        color: Colors.textPrimary,
    },
    // Success Screen
    successContainer: {
        alignItems: "center",
        paddingVertical: 20,
    },
    successIconContainer: {
        width: 72,
        height: 72,
        borderRadius: 36,
        backgroundColor: "rgba(16, 185, 129, 0.15)",
        borderWidth: 1,
        borderColor: "rgba(16, 185, 129, 0.3)",
        alignItems: "center",
        justifyContent: "center",
        marginBottom: 16,
    },
    successTitle: {
        fontSize: 20,
        fontWeight: "700",
        color: Colors.textPrimary,
        marginBottom: 8,
    },
    successMessage: {
        fontSize: 14,
        color: Colors.textSecondary,
        textAlign: "center",
        lineHeight: 22,
        marginBottom: 16,
    },
    skippedNoticeBox: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "rgba(245, 158, 11, 0.1)",
        borderColor: "rgba(245, 158, 11, 0.25)",
        borderWidth: 1,
        borderRadius: 12,
        padding: 12,
        gap: 8,
        marginBottom: 24,
        width: "100%",
    },
    skippedNoticeText: {
        flex: 1,
        fontSize: 12,
        color: Colors.warning,
        lineHeight: 18,
    },
    failedMoviesContainer: {
        width: "100%",
        backgroundColor: "rgba(245, 158, 11, 0.08)",
        borderColor: "rgba(245, 158, 11, 0.25)",
        borderWidth: 1,
        borderRadius: 14,
        padding: 14,
        marginBottom: 20,
    },
    failedHeader: {
        flexDirection: "row",
        alignItems: "center",
        gap: 8,
        marginBottom: 6,
    },
    failedTitle: {
        fontSize: 14,
        fontWeight: "600",
        color: Colors.warning,
    },
    failedDesc: {
        fontSize: 12,
        color: Colors.textSecondary,
        lineHeight: 16,
        marginBottom: 10,
    },
    failedList: {
        maxHeight: 140,
    },
    failedItemRow: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        paddingVertical: 6,
        borderBottomWidth: 1,
        borderBottomColor: "rgba(255, 255, 255, 0.06)",
    },
    failedMovieInfo: {
        flex: 1,
    },
    failedMovieName: {
        fontSize: 13,
        fontWeight: "600",
        color: Colors.textPrimary,
        marginBottom: 2,
    },
    failedMovieReason: {
        fontSize: 11,
        color: Colors.danger,
    },
    doneButton: {
        width: "100%",
        backgroundColor: Colors.primary,
        borderRadius: 12,
        paddingVertical: 14,
        alignItems: "center",
        justifyContent: "center",
    },
    doneButtonText: {
        fontSize: 15,
        fontWeight: "700",
        color: "#FFFFFF",
    },
});
