import { StyleSheet } from "react-native";
import { Colors } from "@/constants/colors";

export const styles = StyleSheet.create({
    container: {
        paddingHorizontal: 20,
        paddingBottom: 32,
        paddingTop: 8,
    },
    subtitle: {
        fontSize: 14,
        color: Colors.textSecondary,
        marginBottom: 20,
        lineHeight: 20,
    },
    errorBanner: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "rgba(239, 68, 68, 0.12)",
        borderColor: "rgba(239, 68, 68, 0.3)",
        borderWidth: 1,
        borderRadius: 12,
        padding: 12,
        marginBottom: 16,
        gap: 10,
    },
    errorText: {
        flex: 1,
        color: Colors.danger,
        fontSize: 13,
        lineHeight: 18,
    },
    inputCard: {
        backgroundColor: Colors.surfaceLight,
        borderRadius: 16,
        padding: 16,
        borderWidth: 1,
        borderColor: Colors.border,
        marginBottom: 16,
    },
    inputLabel: {
        fontSize: 13,
        fontWeight: "600",
        color: Colors.textSecondary,
        marginBottom: 8,
        textTransform: "uppercase",
        letterSpacing: 0.5,
    },
    inputRow: {
        flexDirection: "row",
        alignItems: "center",
        gap: 10,
    },
    textInput: {
        flex: 1,
        backgroundColor: "rgba(255, 255, 255, 0.06)",
        borderWidth: 1,
        borderColor: Colors.border,
        borderRadius: 12,
        paddingHorizontal: 12,
        paddingVertical: 11,
        fontSize: 13,
        color: Colors.textPrimary,
    },
    addButton: {
        backgroundColor: Colors.primary,
        borderRadius: 12,
        paddingHorizontal: 14,
        paddingVertical: 11,
        alignItems: "center",
        justifyContent: "center",
    },
    addButtonDisabled: {
        opacity: 0.5,
    },
    addButtonText: {
        fontSize: 13,
        fontWeight: "700",
        color: "#FFFFFF",
    },
    inputHintText: {
        fontSize: 11.5,
        color: Colors.textSecondary,
        marginTop: 8,
        lineHeight: 16,
    },
    sectionTitle: {
        fontSize: 14,
        fontWeight: "600",
        color: Colors.textPrimary,
        marginBottom: 10,
    },
    playlistsList: {
        maxHeight: 180,
        marginBottom: 16,
    },
    playlistItem: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "rgba(255, 255, 255, 0.04)",
        borderWidth: 1,
        borderColor: Colors.border,
        borderRadius: 12,
        paddingHorizontal: 12,
        paddingVertical: 10,
        marginBottom: 8,
        gap: 10,
    },
    playlistItemText: {
        flex: 1,
        fontSize: 13,
        color: Colors.textPrimary,
    },
    removeButton: {
        padding: 4,
    },
    publicNoticeBox: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "rgba(74, 158, 255, 0.08)",
        borderColor: "rgba(74, 158, 255, 0.2)",
        borderWidth: 1,
        borderRadius: 12,
        padding: 12,
        gap: 8,
        marginBottom: 20,
    },
    publicNoticeText: {
        flex: 1,
        fontSize: 12,
        color: Colors.textSecondary,
        lineHeight: 18,
    },
    importButton: {
        backgroundColor: Colors.primary,
        borderRadius: 12,
        paddingVertical: 14,
        alignItems: "center",
        justifyContent: "center",
    },
    importButtonDisabled: {
        opacity: 0.5,
    },
    importButtonText: {
        fontSize: 15,
        fontWeight: "700",
        color: "#FFFFFF",
    },
    // Progress Screen
    progressContainer: {
        alignItems: "center",
        paddingVertical: 20,
    },
    progressIconContainer: {
        width: 64,
        height: 64,
        borderRadius: 32,
        backgroundColor: "rgba(30, 215, 96, 0.12)",
        borderWidth: 1,
        borderColor: "rgba(30, 215, 96, 0.25)",
        alignItems: "center",
        justifyContent: "center",
        marginBottom: 16,
    },
    progressTitle: {
        fontSize: 17,
        fontWeight: "700",
        color: Colors.textPrimary,
        marginBottom: 8,
        textAlign: "center",
    },
    progressSubtitle: {
        fontSize: 14,
        color: Colors.textSecondary,
        marginBottom: 24,
        textAlign: "center",
    },
    progressBarTrack: {
        width: "100%",
        height: 10,
        backgroundColor: "rgba(255, 255, 255, 0.08)",
        borderRadius: 5,
        overflow: "hidden",
        marginBottom: 14,
    },
    progressBarFill: {
        height: "100%",
        backgroundColor: "#1DB954", // Spotify Green accent
        borderRadius: 5,
    },
    progressStatsRow: {
        flexDirection: "row",
        justifyContent: "space-between",
        width: "100%",
        marginBottom: 20,
    },
    progressStatText: {
        fontSize: 13,
        color: Colors.textSecondary,
        fontWeight: "500",
    },
    progressStatValue: {
        color: Colors.textPrimary,
        fontWeight: "600",
    },
    backgroundInfoBox: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "rgba(74, 158, 255, 0.08)",
        borderRadius: 12,
        padding: 12,
        gap: 10,
        marginBottom: 20,
    },
    backgroundInfoText: {
        flex: 1,
        fontSize: 12,
        color: Colors.textSecondary,
        lineHeight: 18,
    },
    backgroundButton: {
        width: "100%",
        backgroundColor: "rgba(255, 255, 255, 0.08)",
        borderRadius: 12,
        paddingVertical: 14,
        alignItems: "center",
        justifyContent: "center",
        borderWidth: 1,
        borderColor: Colors.border,
    },
    backgroundButtonText: {
        fontSize: 15,
        fontWeight: "600",
        color: Colors.textPrimary,
    },
    // Success Screen
    successContainer: {
        alignItems: "center",
        paddingVertical: 20,
    },
    successIconContainer: {
        width: 72,
        height: 72,
        borderRadius: 36,
        backgroundColor: "rgba(30, 215, 96, 0.15)",
        borderWidth: 1,
        borderColor: "rgba(30, 215, 96, 0.3)",
        alignItems: "center",
        justifyContent: "center",
        marginBottom: 16,
    },
    successTitle: {
        fontSize: 20,
        fontWeight: "700",
        color: Colors.textPrimary,
        marginBottom: 8,
    },
    successMessage: {
        fontSize: 14,
        color: Colors.textSecondary,
        textAlign: "center",
        lineHeight: 22,
        marginBottom: 20,
    },
    failedContainer: {
        width: "100%",
        backgroundColor: "rgba(245, 158, 11, 0.08)",
        borderColor: "rgba(245, 158, 11, 0.25)",
        borderWidth: 1,
        borderRadius: 14,
        padding: 14,
        marginBottom: 20,
    },
    failedHeader: {
        flexDirection: "row",
        alignItems: "center",
        gap: 8,
        marginBottom: 6,
    },
    failedTitle: {
        fontSize: 14,
        fontWeight: "600",
        color: Colors.warning,
    },
    failedDesc: {
        fontSize: 12,
        color: Colors.textSecondary,
        lineHeight: 16,
        marginBottom: 10,
    },
    failedList: {
        maxHeight: 120,
    },
    failedItemRow: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        paddingVertical: 6,
        borderBottomWidth: 1,
        borderBottomColor: "rgba(255, 255, 255, 0.06)",
    },
    failedItemInfo: {
        flex: 1,
    },
    failedItemName: {
        fontSize: 13,
        fontWeight: "600",
        color: Colors.textPrimary,
        marginBottom: 2,
    },
    failedReason: {
        fontSize: 11,
        color: Colors.danger,
    },
    doneButton: {
        width: "100%",
        backgroundColor: Colors.primary,
        borderRadius: 12,
        paddingVertical: 14,
        alignItems: "center",
        justifyContent: "center",
    },
    doneButtonText: {
        fontSize: 15,
        fontWeight: "700",
        color: "#FFFFFF",
    },
});
