import { StyleSheet } from "react-native";
import { Colors } from "@/constants/colors";

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: Colors.background,
    },
    listContent: {
        flexGrow: 1,
        paddingBottom: 32,
    },
    header: {
        paddingHorizontal: 20,
        paddingTop: 16,
        paddingBottom: 14,
        borderBottomWidth: StyleSheet.hairlineWidth,
        borderBottomColor: Colors.border,
        backgroundColor: Colors.background,
    },
    headerTitle: {
        fontSize: 24,
        fontWeight: "800",
        color: Colors.textPrimary,
        letterSpacing: -0.5,
    },
    row: {
        flexDirection: "row",
        alignItems: "center",
        paddingVertical: 14,
        paddingHorizontal: 16,
        borderBottomWidth: StyleSheet.hairlineWidth,
        borderBottomColor: Colors.border,
        backgroundColor: Colors.background,
    },
    unreadRow: {
        backgroundColor: "rgba(255, 128, 0, 0.04)",
    },
    avatarContainer: {
        position: "relative",
        marginRight: 12,
    },
    avatar: {
        width: 46,
        height: 46,
        borderRadius: 23,
        backgroundColor: Colors.surface,
    },
    avatarFallback: {
        width: 46,
        height: 46,
        borderRadius: 23,
        backgroundColor: Colors.surface,
        justifyContent: "center",
        alignItems: "center",
        borderWidth: 1,
        borderColor: Colors.border,
    },
    avatarFallbackText: {
        color: Colors.textPrimary,
        fontSize: 16,
        fontWeight: "600",
    },
    badgeIcon: {
        position: "absolute",
        bottom: -2,
        right: -2,
        width: 18,
        height: 18,
        borderRadius: 9,
        justifyContent: "center",
        alignItems: "center",
        borderWidth: 1.5,
        borderColor: Colors.background,
    },
    badgeFollow: {
        backgroundColor: "#3B82F6",
    },
    badgeLike: {
        backgroundColor: "#EF4444",
    },
    badgeComment: {
        backgroundColor: "#10B981",
    },
    badgeRequest: {
        backgroundColor: Colors.primary,
    },
    contentContainer: {
        flex: 1,
        justifyContent: "center",
        marginRight: 8,
    },
    actorName: {
        color: Colors.textPrimary,
        fontWeight: "700",
        fontSize: 14,
    },
    messageText: {
        color: Colors.textSecondary,
        fontSize: 14,
        lineHeight: 19,
    },
    timeText: {
        color: Colors.textMuted,
        fontSize: 12,
        marginTop: 4,
    },
    targetThumbnail: {
        width: 42,
        height: 42,
        borderRadius: 6,
        backgroundColor: Colors.surface,
        borderWidth: 1,
        borderColor: Colors.border,
    },
    targetPlaceholder: {
        justifyContent: "center",
        alignItems: "center",
        backgroundColor: Colors.surface,
    },
    unreadDot: {
        width: 8,
        height: 8,
        borderRadius: 4,
        backgroundColor: Colors.primary,
        marginLeft: 6,
    },
    actionsContainer: {
        flexDirection: "row",
        alignItems: "center",
        gap: 8,
    },
    acceptButton: {
        backgroundColor: Colors.primary,
        paddingHorizontal: 14,
        paddingVertical: 8,
        borderRadius: 8,
        justifyContent: "center",
        alignItems: "center",
    },
    acceptButtonText: {
        color: "#FFFFFF",
        fontSize: 13,
        fontWeight: "600",
    },
    declineButton: {
        backgroundColor: Colors.surface,
        borderWidth: 1,
        borderColor: Colors.border,
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderRadius: 8,
        justifyContent: "center",
        alignItems: "center",
    },
    declineButtonText: {
        color: Colors.textSecondary,
        fontSize: 13,
        fontWeight: "600",
    },
    statusBadge: {
        paddingHorizontal: 10,
        paddingVertical: 6,
        borderRadius: 6,
        backgroundColor: Colors.surface,
    },
    statusBadgeText: {
        fontSize: 12,
        fontWeight: "500",
        color: Colors.textMuted,
    },
    emptyContainer: {
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
        paddingHorizontal: 32,
        paddingVertical: 80,
    },
    emptyIconWrapper: {
        width: 80,
        height: 80,
        borderRadius: 40,
        backgroundColor: "rgba(255, 255, 255, 0.04)",
        justifyContent: "center",
        alignItems: "center",
        marginBottom: 20,
    },
    emptyTitle: {
        fontSize: 18,
        fontWeight: "700",
        color: Colors.textPrimary,
        marginBottom: 8,
        textAlign: "center",
    },
    emptySubtitle: {
        fontSize: 14,
        color: Colors.textSecondary,
        textAlign: "center",
        lineHeight: 20,
    },
});
